version: '3'
services:
  api:
    container_name: my-api
    env_file:
      - .env
    build: .
    ports:
      - 5050:${SERVER_PORT}/tcp
    links:
      - postgres
  postgres:
    container_name: my-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD
      - POSTGRES_DB=${POSTGRES_DB}
    image: library/postgres:latest
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}/tcp
  flyway:
    container_name: my-flyway
    environment:
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
      - FLYWAY_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      - FLYWAY_SCHEMAS=flyway,${POSTGRES_SCHEMA}
      - FLYWAY_GROUP=true
      - FLYWAY_LICENSE_KEY=${FLYWAY_LICENSE_KEY}
      - FLYWAY_EDITION=${FLYWAY_EDITION}
    image: flyway/flyway:latest
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
      volumes:
        - $PWD/sql_versions:/flyway/sql
      depends_on:
        - postgres      image: flyway/flyway:latest
      command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
      volumes:
        - $PWD/sql_versions:/flyway/sql
      depends_on:
        - postgres