##########################
## Migration Operations ##
##########################

# Variables
MIGRATION_MESSAGE ?= "New migration"
ALEMBIC = alembic

# Targets
.PHONY: makemigrations migrate

# Create a new migration script with an autogenerated message
plan-migration:
	@echo "Creating new migration script..."
	$(ALEMBIC) revision --autogenerate -m "$(MIGRATION_MESSAGE)"
	@echo "Migration script created."

# Apply all pending migrations
apply-migrations:
	@echo "Applying migrations..."
	$(ALEMBIC) upgrade head
	@echo "Migrations applied."

# Show the current revision
current-revisions:
	@echo "Current database revision:"
	$(ALEMBIC) current

# Show migration history
migration-history:
	@echo "Migration history:"
	$(ALEMBIC) history

# Rollback the last migration
rollback-last-migration:
	@echo "Rolling back the last migration..."
	$(ALEMBIC) downgrade -1
	@echo "Last migration rolled back."

##########################
##   Local Development  ##
##########################

lint-check:
	ruff check .

lint-fix:
	ruff check --fix .

format:
	ruff format .

run:
	python main.py